### ISSUE TITLE
REST lake ingestion 1.0 release

### ISSUE THREAD

**Issue by mike-audi** [tiki/publish#2]
Test, fix, and deploy updated rest ingestion endpoints `/shopify` and `/microblink` for public availability. This includes schema resolution, writing individual files to a staging bucket, and then the files being aggregated and written as parquet files to the ocean lake. 

Issues:
- [ ] https://github.com/tiki/publish-data-rest/issues/1
- [x] https://github.com/tiki/publish-data-rest/issues/5
- [ ] https://github.com/tiki/publish-data-rest/issues/4
- [x] https://github.com/tiki/publish-data-load/issues/22
- [x] https://github.com/tiki/publish-data-rest/issues/7
- [x] https://github.com/tiki/publish-data-rest/issues/8
- [x] https://github.com/tiki/publish-data-rest/issues/9
- [x] https://github.com/tiki/apps-shopify-extensions/issues/122

**Comment by ricardobrg** [comment]
@mike-audi is it still valid?
